# Generated by Django 4.2.9 on 2024-08-03 07:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0002_rename_recipe_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Todos',
        ),
        migrations.RenameField(
            model_name='todos',
            old_name='note_description',
            new_name='todo_description',
        ),
        migrations.RenameField(
            model_name='todos',
            old_name='note_name',
            new_name='todo_name',
        ),
    ]
